package com.crissnm.registrousuarios.DepYmuni
object municipio {
    val municipiosMap = mapOf(
        1 to mapOf(
            1 to "Guatemala",
            2 to "Santa Catarina Pinula",
            3 to "San José Pinula",
            4 to "San José del Golfo",
            5 to "Palencia",
            6 to "Chinautla",
            7 to "San Pedro Ayampuc",
            8 to "Mixco",
            9 to "San Pedro Sacatepéquez",
            10 to "San Juan Sacatepéquez",
            11 to "San Raimundo",
            12 to "Chuarrancho",
            13 to "Fraijanes",
            14 to "Amatitlán",
            15 to "Villa Nueva",
            16 to "Villa Canales",
            17 to "Petapa"
        ),
        2 to mapOf(
            1 to "Guastatoya",
            2 to "Morazán",
            3 to "San Agustín Acasaguastlán",
            4 to "San Cristobal Acasaguastlán",
            5 to "El Jícaro",
            6 to "Sansare",
            7 to "Sanarate",
            8 to "San Antonio La Paz"
        ),
        3 to mapOf(
            1 to "Antigua Guatemala",
            2 to "Jocotenango",
            3 to "Pastores",
            4 to "Sumpango",
            5 to "Santo Domingo Xenacoj",
            6 to "Santiago Sacatepéquez",
            7 to "San Bartolomé Milpas Altas",
            8 to "San Lucas Sacatepéquez",
            9 to "Santa Lucia Milpas Altas",
            10 to "Magdalena Milpas Altas",
            11 to "Santa María de Jesús",
            12 to "Ciudad Vieja",
            13 to "San Miguel Dueñas",
            14 to "Alotenango",
            15 to "San Antonio Aguas Calientes",
            16 to "Santa Catalina Barahona"
        ),
        4 to mapOf(
            1 to "Chimaltenango",
            2 to "San José Poaquil",
            3 to "San Martín Jilotepeque",
            4 to "Comalapa",
            5 to "Santa Apolonia",
            6 to "Tecpan Guatemala",
            7 to "Patzún",
            8 to "Pochuta",
            9 to "Patzicía",
            10 to "Santa Cruz Balanya",
            11 to "Acatenango",
            12 to "Yepocapa",
            13 to "San Andrés Itzapa",
            14 to "Parramos",
            15 to "Zaragoza",
            16 to "El Tejar"
        ),
        5 to mapOf(
            1 to "Escuintla",
            2 to "Santa Lucía Cotzumalguapa",
            3 to "La Democracia",
            4 to "Siquinalá",
            5 to "Masagua",
            6 to "Tiquisate",
            7 to "La Gomera",
            8 to "Guanagazapa",
            9 to "San José",
            10 to "Iztapa",
            11 to "Palín",
            12 to "San Vicente Pacaya",
            13 to "Nueva Concepción"
        ),
        6 to mapOf(
            1 to "Cuilapa",
            2 to "Barberena",
            3 to "Santa Rosa de Lima",
            4 to "Casillas",
            5 to "San Rafael Las Flores",
            6 to "Oratorio",
            7 to "San Juan Tecuaco",
            8 to "Chiquimulilla",
            9 to "Taxisco",
            10 to "Santa María Ixhuatán",
            11 to "Guazacapán",
            12 to "Santa Cruz Naranjo",
            13 to "Pueblo Nuevo Viñas",
            14 to "Nueva Santa Rosa"
        ),
        7 to mapOf(
            1 to "Sololá",
            2 to "San José Chacayá",
            3 to "Santa María Visitación",
            4 to "Santa Lucía Utatlán",
            5 to "Nahualá",
            6 to "Santa Catarina Ixtahuacán",
            7 to "Santa Clara La Laguna",
            8 to "Concepción",
            9 to "San Andrés Semetabaj",
            10 to "Panajachel",
            11 to "Santa Catarina Palopó",
            12 to "San Antonio Palopó",
            13 to "San Lucas Tolimán",
            14 to "Santa Cruz La Laguna",
            15 to "San Pablo La Laguna",
            16 to "San Marcos La Laguna",
            17 to "San Juan La Laguna",
            18 to "San Pedro La Laguna",
            19 to "Santiago Atitlán",
        ),
        8 to mapOf(
            1 to "Totonicapán",
            2 to "San Cristóbal Totonicapán",
            3 to "San Francisco El Alto",
            4 to "San Andrés Xecul",
            5 to "Momostenango",
            6 to "Santa María Chiquimula",
            7 to "Santa Lucía La Reforma",
            8 to "San Bartolo",
        ),
        9 to mapOf(
            1 to "Quetzaltenango",
            2 to "Salcajá",
            3 to "Olintepeque",
            4 to "San Carlos Sija",
            5 to "Sibilia",
            6 to "Cabricán",
            7 to "Cajolá",
            8 to "San Miguel Sigüilá",
            9 to "San Juan Ostuncalco",
            10 to "San Mateo",
            11 to "Concepción Chiquirichapa",
            12 to "San Martín Sacatepéquez",
            13 to "Almolonga",
            14 to "Cantel",
            15 to "Huitán",
            16 to "Zunil",
            17 to "Colomba",
            18 to "San Francisco La Unión",
            19 to "El Palmar",
            20 to "Coatepeque",
            21 to "Génova",
            22 to "Flores Costa Cuca",
            23 to "La Esperanza",
            24 to "Palestina de Los Altos"
        ),
        10 to mapOf(
            1 to "Mazatenango",
            2 to "Cuyotenango",
            3 to "San Francisco Zapotitlán",
            4 to "San Bernardino",
            5 to "San José El Idolo",
            6 to "Santo Domingo Suchitepéquez",
            7 to "San Lorenzo",
            8 to "Samayac",
            9 to "San Pablo Jocopilas",
            10 to "San Antonio Suchitepéquez",
            11 to "San Miguel Panán",
            12 to "San Gabriel",
            13 to "Chicacao",
            14 to "Patulul",
            15 to "Santa Bárbara",
            16 to "San Juan Bautista",
            17 to "Santo Tomás La Unión",
            18 to "Zunilito",
            19 to "Pueblo Nuevo",
            20 to "Río Bravo"
        ),
        11 to mapOf(
            1 to "Retalhuleu",
            2 to "San Sebastián",
            3 to "Santa Cruz Mulua",
            4 to "San Martín Zapotitlán",
            5 to "San Felipe",
            6 to "San Andrés Villa Seca",
            7 to "Champerico",
            8 to "Nuevo San Carlos",
            9 to "El Asintal"
        ),
        12 to mapOf(
            1 to "San Marcos",
            2 to "San Pedro Sacatepéquez ",
            3 to "San Antonio Sacatepéquez",
            4 to "Comitancillo",
            5 to "San Miguel Ixtahuacán",
            6 to "Concepción Tutuapa",
            7 to "Tacaná",
            8 to "Sibinal",
            9 to "Tajumulco",
            10 to "Tejutla",
            11 to "San Rafael Pie de la Cuesta",
            12 to "Nuevo Progreso",
            13 to "El Tumbador",
            14 to "El Rodeo",
            15 to "Malacatán",
            16 to "Catarina",
            17 to "Ayutla",
            18 to "Ocós",
            19 to "San Pablo",
            20 to "El Quetzal",
            21 to "La Reforma",
            22 to "Pajapita",
            23 to "Ixchiguán",
            24 to "San José Ojetenam",
            25 to "San Cristóbal Cucho",
            26 to "Sipacapa",
            27 to "Esquipulas Palo Gordo",
            28 to "Río Blanco",
            29 to "San Lorenzo",

        ),
        13 to mapOf(
            1 to "Huehuetenango",
            2 to "Chiantla",
            3 to "Malacatancito",
            4 to "Cuilco",
            5 to "Nentón",
            6 to "San Pedro Necta",
            7 to "Jacaltenango",
            8 to "Soloma",
            9 to "San Ildefonso Ixtahuacán",
            10 to "Santa Bárbara",
            11 to "La Libertad",
            12 to "La Democracia",
            13 to "San Miguel Acatán",
            14 to "San Rafael La Independencia",
            15 to "Todos Santos Cuchumatán",
            16 to "San Juan Atitán",
            17 to "Santa Eulalia",
            18 to "San Mateo Ixtatán",
            19 to "Colotenango",
            20 to "San Sebastián Huehuetenango",
            21 to "Tectitán",
            22 to "Concepción Huista",
            23 to "San Juan Ixcoy",
            24 to "San Antonio Huista",
            25 to "San Sebastián Coatán",
            26 to "Santa Cruz Barillas",
            27 to "Aguacatán",
            28 to "San Rafael Petzal",
            29 to "San Gaspar Ixchil",
            30 to "Santiago Chimaltenango",
            31 to "Santa Ana Huista",
        ),
        14 to mapOf(
            1 to "Santa Cruz del Quiché",
            2 to "Quiché",
            3 to "Chinique",
            4 to "Zacualpa",
            5 to "Chajul",
            6 to "Chichicastenango",
            7 to "Patzité",
            8 to "San Antonio Ilotenango",
            9 to "San Pedro Jocopilas",
            10 to "Cunén",
            11 to "San Juan Cotzal",
            12 to "Joyabaj",
            13 to "Nebaj",
            14 to "San Andrés Sajcabajá",
            15 to "Uspantán",
            16 to "Sacapulas",
            17 to "San Bartolomé Jocotenango",
            18 to "Canillá",
            19 to "Chicamán",
            20 to "Ixcán",
            21 to "Pachalum"
        ),
        15 to mapOf(
            1 to "Salamá",
            2 to "San Miguel Chicaj",
            3 to "Rabinal",
            4 to "Cubulco",
            5 to "Granados",
            6 to "Santa Cruz El Chol",
            7 to "San Jerónimo",
            8 to "Purulhá"
        ),
        16 to mapOf(
            1 to "Cobán",
            2 to "Santa Cruz Verapaz",
            3 to "San Cristóbal Verapaz",
            4 to "Tactic",
            5 to "Tamahú",
            6 to "San Miguel Tucuruí",
            7 to "Panzós",
            8 to "Senahú",
            9 to "San Pedro Carchá",
            10 to "San Juan Chamelco",
            11 to "Lanquín",
            12 to "Cahabón",
            13 to "Chisec",
            14 to "Chahal",
            15 to "Fray Bartolomé de las Casas",
        ),
        17 to mapOf(
            1 to "Flores",
            2 to "San José",
            3 to "San Benito",
            4 to "San Andrés",
            5 to "La Libertad",
            6 to "San Francisco",
            7 to "Santa Ana",
            8 to "Dolores",
            9 to "San Luis",
            10 to "Sayaxché",
            11 to "Melchor de Mencos",
            12 to "Poptún",
        ),
        18 to mapOf(
            1 to "Puerto Barrios",
            2 to "Livingston",
            3 to "El Estor",
            4 to "Morales",
            5 to "Los Amates",
        ),
        19 to mapOf(
            1 to "Zacapa",
            2 to "Estanzuela",
            3 to "Río Hondo",
            4 to "Gualán",
            5 to "Teculután",
            6 to "Usumatlán",
            7 to "Cabañas",
            8 to "San Diego",
            9 to "La Unión",
            10 to "Huité",
        ),
        20 to mapOf(
            1 to "Chiquimula",
            2 to "San José La Arada",
            3 to "San Juan Ermita",
            4 to "Jocotán",
            5 to "Camotán",
            6 to "Olopa",
            7 to "Esquipulas",
            8 to "Concepción Las Minas",
            9 to "Quezaltepeque",
            10 to "San Jacinto",
            11 to "Ipala",
        ),
        21 to mapOf(
            1 to "Jalapa",
            2 to "San Pedro Pinula",
            3 to "San Luis Jilotepeque",
            4 to "San Manuel Chaparrón",
            5 to "San Carlos Alzatate",
            6 to "Monjas",
            7 to "Mataquescuintla",
        ),
        22 to mapOf(
            1 to "Jutiapa",
            2 to "El Progreso",
            3 to "Santa Catarina Mita",
            4 to "Agua Blanca",
            5 to "Asunción Mita",
            6 to "Yupiltepeque",
            7 to "Atescatempa",
            8 to "Jerez",
            9 to "El Adelanto",
            10 to "Zapotitlán",
            11 to "Comapa",
            12 to "Jalpatagua",
            13 to "Conguaco",
            14 to "Moyuta",
            15 to "Pasaco",
            16 to "San José Acatempa",
            17 to "Quezada",
        )
    )
}